### ISSUE TITLE
Unhandled Promise Rejection Warning

### ISSUE THREAD

**Issue by italopessoa** [ifactory-solutions/awesome-react-app#11]
Since there's already an `f1` folder, `create-react-app` raises an error with a message containing suggestions on how to fix it, but the error is not handled by `awesome-react-app` and this causes the message below:

> (node:14180) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): undefined

![image](https://user-images.githubusercontent.com/9323529/31256783-0160528a-aa0b-11e7-8395-fd2c072da106.png)

**UPDATE:** this is happening every time a promise is rejected but the code doesn't handle it.
```js
function unhandledPromiseRejection(promise) {
   promise.then(() => console.log('success'))//Unhandled Promise Rejection Warning
}
```
every promise that behaves like the code above should be fixed.

to test your implementation
install awesome-react-app `npm i -g awesome-react-app`
create a react project `awesome-react-app project`
try to create a project with the same name in the same folder

**Comment by swyxio** [comment]
claiming!

**Comment by jvcjunior** [comment]
Go ahead @sw-yx!! Feel free to get this one if you want to! Just let us know, please!

**Comment by swyxio** [comment]
passed to my buddy seth to make his first PR - please be kind! (but also we didnt have a lot of guidance on what exactly to handle)

**Comment by italopessoa** [comment]
nice @sw-yx. and don't worry, we'll do our the best to help him

**Comment by jvcjunior** [comment]
Great team work @sw-yx !! Let us know if you have questions. We all are here to help! we appreciate your efforts.
