### ISSUE TITLE
Create Contributing file

### ISSUE THREAD

**Issue by paulonotz0r** [ifactory-solutions/awesome-react-app#17]
Create `CONTRIBUTING.md` to help new contributors how to get started and contribute in the right way.

**Comment by harleo** [comment]
Hey, working on that right now.

**Comment by jvcjunior** [comment]
Awesome @harleo ! Let us know if you have any questions! Thank you! ❤️

**Comment by paulonotz0r** [comment]
Nice, @harleo! 😃

**Comment by harleo** [comment]
Hope this helps a little.
Also added a code of conduct.
#20

**Comment by italopessoa** [comment]
@jouderianjr  Does he can add the instructions about which branches should be used to create PRs?
