### ISSUE TITLE
Add commit lint

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/awesome-react-app#43]

**Comment by ceejtron** [comment]
I'll take this

**Comment by jouderianjr** [comment]
@ceejtron Awesome! Use this PR as reference: https://github.com/ifactory-solutions/inside-client/pull/8

**Comment by sonali-moholkar** [comment]
is this still open?

**Comment by paulonotz0r** [comment]
Hey, @smoholkar! @ceejtron already worked on this. But feel free to give suggestions, contributions, discuss anything about the project. 

Thank you!
